const data = {
  _cft: [1811668587, 2687],
  timestamp: 1716952315,
  shoporders: [
    {
      shop: { shopid: 24710134 },
      items: [
        {
          itemid: 5943251527,
          modelid: 70370935107,
          quantity: 1,
          add_on_deal_id: 199230711468248,
          is_add_on_sub_item: false,
          item_group_id: "199230711468248",
          insurances: [],
          channel_exclusive_info: { source_id: 0, token: "" },
          supports_free_returns: true,
          free_return_eligible: false,
          com_eligible: true,
        },
        {
          itemid: 24476689401,
          modelid: 232790357871,
          quantity: 1,
          add_on_deal_id: 199230711468248,
          is_add_on_sub_item: true,
          item_group_id: "199230711468248",
          insurances: [],
          channel_exclusive_info: { source_id: 0, token: "" },
          supports_free_returns: true,
          free_return_eligible: false,
          com_eligible: true,
        },
        {
          itemid: 25756866194,
          modelid: 168043146221,
          quantity: 1,
          add_on_deal_id: 199230711468248,
          is_add_on_sub_item: false,
          item_group_id: "199230711468248",
          insurances: [],
          channel_exclusive_info: { source_id: 0, token: "" },
          supports_free_returns: true,
          free_return_eligible: false,
          com_eligible: true,
        },
      ],
      shipping_id: 1,
    },
  ],
  selected_payment_channel_data: {
    version: 2,
    option_info: "",
    channel_id: 5002900,
    channel_item_option_info: { external_channel_item_id: 113740327 },
    text_info: {},
    ros_opt_in: false,
  },
  promotion_data: {
    use_coins: false,
    free_shipping_voucher_info: {
      free_shipping_voucher_id: 0,
      free_shipping_voucher_code: "",
      disabled_reason: null,
      disabled_reason_code: 0,
      banner_info: { msg: "", learn_more_msg: "" },
      required_be_channel_ids: [],
      required_spm_channels: [],
    },
    platform_vouchers: [],
    shop_vouchers: [
      {
        shopid: 24710134,
        promotionid: 876320808943616,
        voucher_code: "COOLMTE30",
      },
    ],
    check_shop_voucher_entrances: true,
    auto_apply_platform_voucher: false,
    auto_apply_shop_voucher: false,
  },
  fsv_selection_infos: [],
  device_info: {
    device_id: "",
    device_fingerprint: "",
    tongdun_blackbox: "",
    buyer_payment_info: {},
  },
  buyer_info: {
    kyc_info: null,
    checkout_email: "",
    spl_activation_status: 0,
    authorize_to_leave_preference: 0,
  },
  cart_type: 0,
  client_id: 0,
  client_event_info: {
    is_platform_voucher_changed: false,
    is_fsv_changed: false,
    recommend_payment_preselect_type: 0,
    recommend_shipping_preselect: false,
  },
  tax_info: { tax_id: "" },
  shipping_orders: [
    {
      sync: true,
      buyer_address_data: {
        addressid: 200023707,
        address_type: 0,
        tax_address: "",
      },
      selected_logistic_channelid: 5001,
      shipping_id: 1,
      shoporder_indexes: [0],
      selected_preferred_delivery_time_slot_id: null,
      selected_preferred_delivery_window: {},
      prescription_info: { images: null },
      fulfillment_info: {
        fulfillment_flag: 64,
        fulfillment_source: "VNZ",
        managed_by_sbs: false,
        order_fulfillment_type: 2,
        warehouse_address_id: 13873358,
        is_from_overseas: false,
      },
    },
  ],
  order_update_info: {},
  checkout_price_data: {
    merchandise_subtotal: 37800000000,
    shipping_subtotal_before_discount: 1280000000,
    shipping_discount_subtotal: 0,
    shipping_subtotal: 1280000000,
    tax_payable: 0,
    tax_exemption: 0,
    import_tax_amount: 0,
    icms_amount: 0,
    iof_amount: 0,
    shipping_sst_amount: null,
    custom_tax_subtotal: 0,
    promocode_applied: 3000000000,
    credit_card_promotion: null,
    shopee_coins_redeemed: null,
    bundle_deals_discount: null,
    price_adjustment: null,
    buyer_txn_fee: 0,
    buyer_service_fee: 0,
    insurance_subtotal: 0,
    insurance_before_discount_subtotal: 0,
    insurance_discount_subtotal: 0,
    vat_subtotal: 0,
    payment_plan: null,
    total_payable: 36080000000,
  },
};
export default data;
